// This file is generated by log_generate.sh, don't edit it.

#ifndef __LOG_DEFINE_H__
#define __LOG_DEFINE_H__

#include "eli_log/eli_log.h"

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

LOG_LEVEL get_module_log_level_PROFINET(void);
const char* get_module_log_name_PROFINET(void);

#define DEBUG_LOG_LEVEL() get_module_log_level_PROFINET()
#define DEBUG_LOG_NAME() get_module_log_name_PROFINET()

#ifdef __cplusplus
}
#endif  // __cplusplus

#endif  // __LOG_DEFINE_H__
