#ifndef __PROFINET_H__
#define __PROFINET_H__

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

#include "profinet/pnet.h"

enum PNET_STATE
{ 
  PNET_STATE_STOP, 
  PNET_STATE_RUN, 
  PNET_STATE_CONNECT, 
  PNET_STATE_ERROR, 
  PNET_STATE_START 
};

enum PNET_LOSE_MODULE_ACTION
{
  PNET_LOSE_MODULE_ACTION_IGNORE,
  PNET_LOSE_MODULE_ACTION_PAUSE,
  PNET_LOSE_MODULE_ACTION_STOP  
};

enum PNET_MODULE
{
  PNET_MODULE_STATE = PNSTATION_MODULE_STATE,
  PNET_MODULE_IO = PNSTATION_MODULE_IO,
  PNET_MODULE_JOINTS = PNSTATION_MODULE_JOINTS,
  PNET_MODULE_TCP = PNSTATION_MODULE_TCP,
  PNET_MODULE_BIT = PNSTATION_MODULE_BIT,
  PNET_MODULE_INT = PNSTATION_MODULE_INT,
  PNET_MODULE_FLOAT = PNSTATION_MODULE_FLOAT,
  PNET_MODULE_O_IO = PNSTATION_MODULE_O_IO,
  PNET_MODULE_O_REG1 = PNSTATION_MODULE_O_REG1,
  PNET_MODULE_O_REG2 = PNSTATION_MODULE_O_REG2,
  PNET_MODULE_INDEX_MAX = PNSTATION_MODULE_INDEX_MAX,
};

void rtsi_pnet_init() ;

void rtsi_pnet_uninit() ;


#ifdef __cplusplus
}
#endif  // __cplusplus

#endif